### ISSUE TITLE
Getting an error while invoking the utility

### ISSUE THREAD

**Issue by ashish-kakkar** [d1soft/mysql-workbench-html-doc-generator#2]
Hi

I have installed the script and when I am trying to invoke the utility I am getting this error: "error calling python module function ModelHtmlDocumentation.documentation

![image](https://user-images.githubusercontent.com/7764878/90610310-de9fc700-e222-11ea-9467-37fac1a03254.png)

May you please help to resolve the same. I am using Mysql workbench 8.0.15

**Comment by ashish-kakkar** [comment]
Adding the workbench log:

14:09:31 [ERR][         python]: error calling ModelHtmlDocumentation.documentationTraceback (most recent call last):
14:09:31 [ERR][         python]:   File "C:\Users\Ashish\AppData\Roaming\MySQL\Workbench\modules\d1-diagram-html-doc-generator_grt.py", line 22, in documentation
14:09:31 [ERR][         python]:     text += writeTableDoc(figure.table)
14:09:31 [ERR][         python]:   File "C:\Users\Ashish\AppData\Roaming\MySQL\Workbench\modules\d1-diagram-html-doc-generator_grt.py", line 46, in writeTableDoc
14:09:31 [ERR][         python]:     text += writeColumnDoc(column, table)
14:09:31 [ERR][         python]:   File "C:\Users\Ashish\AppData\Roaming\MySQL\Workbench\modules\d1-diagram-html-doc-generator_grt.py", line 127, in writeColumnDoc
14:09:31 [ERR][         python]:     if fk.columns[0].name == column.name:
14:09:31 [ERR][         python]: IndexError: list index out of range
14:09:31 [ERR][            grt]: Error executing plugin info.d1.wb.htmldocgen: error calling Python module function ModelHtmlDocumentation.documentation	
14:09:31 [ERR][      WBContext]: error calling Python module function ModelHtmlDocumentation.documentation
